[package]
name = "xsoverlay-notifications"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-error = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
